### ISSUE TITLE
Tailwind 4 Beta Version with UI Framework

### ISSUE THREAD

**Issue by dzaky-pr** [kristoferlund/ic-vite-react-next#2]
Can we downgrade Tailwind to version 3 to use UI frameworks like shadcn, Radix UI, or similar ones? Or do you have other suggestions that are supported by Tailwind version 4?

**Comment by kristoferlund** [comment]
@dzaky-pr As far as I know, no UI frameworks yet support Tailwind 4, since it is still in beta. Once released, I expect many to adopt it. But for now, you would have to roll your own components.

**Comment by kristoferlund** [comment]
Alpha version of DaisyUI apparently supports it. But with alpha reliability.

https://daisyui.com/blog/daisyui-5-alpha/

**Comment by dzaky-pr** [comment]
Can I downgrade the Tailwind version in this repository to use a UI framework? If yes, what’s the process or flow for doing it? Thank you in advance!

**Comment by kristoferlund** [comment]
@dzaky-pr I am sure you can, without too much headache. I have not looked into this though.
